### ISSUE TITLE
Difficulties pushing to github

### ISSUE THREAD

**Issue by mitchell-thomann** [mitchell-thomann/doseCombR#1]
@enantz-lilly
@wlandau

I'm still have difficulties with this repository.  I am now connected via SSH.  This is the message that I get when I push to github:

<img width="641" alt="screen shot 2018-12-21 at 12 30 25 pm" src="https://user-images.githubusercontent.com/44234773/50355459-c1ca6200-051c-11e9-8c16-529175c4f505.png">

Both my local and global and setting are shown below:

<img width="555" alt="screen shot 2018-12-21 at 12 29 52 pm" src="https://user-images.githubusercontent.com/44234773/50355490-e58da800-051c-11e9-8423-f56ee3253f32.png">

I'm stuck, any ideas?

**Comment by wlandau** [comment]
Maybe try changing `remote.origin.url`? 

- https://www.freecodecamp.org/forum/t/need-your-help-with-github-permission-denied-to-my-own-repo/17421/2
- https://www.a2hosting.com/kb/developer-corner/version-control-systems1/403-forbidden-error-message-when-you-try-to-push-to-a-github-repository
- https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

**Comment by mitchell-thomann** [comment]
Thanks, that worked!
